#!/bin/sh
# Script to run `make` command inside a centos7 docker container
# Files generated by `make` will be written to the current directory on the host
# Execute the container using: sudo docker run --rm=true -e "USERID=${UID}" -v `pwd`:/src:rw centos:centos7 /bin/sh -c "cd src && ./deploy/make-on-centos7.sh"

# Add a default user to squash unknown user errors during rpmbuild
adduser --uid "${USERID}" hostuser

# scipy package build fails when run from the host directory
# so copy and run from inside the container
cp -r . /python-dependencies
pushd /python-dependencies > /dev/null

# Install dependencies
yum -y clean all
yum -y clean expire-cache
yum -y install rpm-build gcc gcc-c++ make git wget unzip gcc-gfortran libquadmath libXt-devel libjpeg-devel zlib-devel freetype-devel epel-release
yum -y install python3-rpm-macros python3 python3-devel python3-setuptools atlas-devel lapack-devel openblas-devel openblas lapack

# Run make command as the default user so that generated files aren't owned by root
# Other packages depend on numpy, so make it manually first
make prereq
rpm -i python3-numpy-*.rpm
rpm -i python3-pybind11-*.rpm
rpm -i python3-serpent-*.rpm

make general
make web

# Copy packages back to the host directory

cp *.rpm /src/
chown hostuser:hostuser /src/*.rpm

popd > /dev/null
