#!/bin/sh
# Script to run `make` command inside a centos7 docker container
# Files generated by `make` will be written to the current directory on the host
# Execute the container using: sudo docker run --rm=true -e "USERID=${UID}" -v `pwd`:/src:rw centos:centos7 /bin/sh -c "cd src && ./deploy/make-on-centos7.sh"

# Add a default user to squash unknown user errors during rpmbuild
adduser --uid "${USERID}" hostuser

# Install dependencies
yum -y clean all
yum -y clean expire-cache
yum -y install rpm-build gcc make git wget unzip atlas-devel lapack-devel gcc-gfortran libquadmath libXt-devel libjpeg-devel zlib-devel freetype-devel epel-release
yum -y install python3-rpm-macros python36 python36-devel python36-setuptools

# Run make command as the default user so that generated files aren't owned by root
# Other packages depend on numpy, so make it manually first
su hostuser -c "make numpy"
rpm -i python36-numpy-*.rpm
su hostuser -c "make py36"

# Legacy packages
#yum -y install python34-pip python34-devel python34-numpy
#pip3 install py2pack
#su hostuser -c "make py34"
